WebSite/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):

    title = StringField('Title', validators=[DataRequired()])

    content = TextAreaField('Content', validators=[DataRequired()])

    submit = SubmitField('Post')

WebSite/main/routes.py
from flask import render_template, request, Blueprint
from flask_login import login_required, current_user
from WebSite.models import Post

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/about')
def about():
    return render_template('about.html')

# Rutas de aplicación y de usuario

@main.route('/home')
@login_required
def home():
    posts = Post.query.all()

    if current_user.is_authenticated:

        page = request.args.get('page', 1, type=int)

        return render_template('home.html', posts=posts)
        
    else:

        return redirect(url_for('users.login'))

WebSite/post/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from WebSite import db
from WebSite.models import Post
from WebSite.post.forms import PostForm

post = Blueprint('post', __name__)


@post.route("/post/<int:post_id>")
def posts(post_id):

    post = Post.query.get_or_404(post_id)

    return render_template('post.html', title=post.title, post=post)

@post.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):

    post = Post.query.get_or_404(post_id)

    if post.author != current_user:

        abort(403)

    db.session.delete(post)

    db.session.commit()

    flash('Tu publicacion fue elmininada!', 'success')

    return redirect(url_for('main.home'))


@post.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()

    if form.validate_on_submit():

        post = Post(title=form.title.data, content=form.content.data, author=current_user)

        db.session.add(post)

        db.session.commit()

        flash('Tu publicacion fue realizada!', 'success')

        return redirect(url_for('main.home'))

    return render_template('create_post.html', title='Nuevo Post', form=form, legend='New Post')

@post.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):

    post = Post.query.get_or_404(post_id)

    if post.author != current_user:

        abort(403)

    form = PostForm()

    if form.validate_on_submit():

        post.title = form.title.data

        post.content = form.content.data

        db.session.commit()

        flash('Tu publicacion fue editada!', 'success')

        return redirect(url_for('main.home', post_id=post.id))

    elif request.method == 'GET':

        form.title.data = post.title

        form.content.data = post.content

    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

WebSite/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from WebSite import db, bcrypt
from WebSite.models import User, Post, Chat
from WebSite.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm)
from flask_socketio import send

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:

        return redirect(url_for('main.home'))

    form = RegistrationForm()

    if form.validate_on_submit():

        # Encripta la contraseña
        h_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        user = User(username=form.username.data, email=form.email.data, password=h_password)

        # Registra los datos del usuario
        db.session.add(user)
        db.session.commit()

        flash(f'Se ha creado una cuenta para {form.username.data}', 'success')

        return redirect(url_for('users.login'))

    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:

        return redirect(url_for('main.home'))

    form = LoginForm()

    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        # Compara la encriptación de las contraseña con la almacenada en la base de datos
        if user and bcrypt.check_password_hash(user.password, form.password.data):

            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')

            return redirect(next_page) if next_page else redirect(url_for('main.home'))

        else:

            flash('Inicio de sesión fallido. Verifique el email y la contraseña.', 'danger')

    return render_template('login.html', title='Inicia Sesión', form=form)


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateAccountForm()

    if form.validate_on_submit():

        if form.picture.data:

            picture_file = save_picture(form.picture.data)

            current_user.image_file = picture_file
        
        current_user.username = form.username.data
        
        current_user.email = form.email.data

        db.session.commit()

        flash('Tu perfil ha sido actualizado!', 'success')

        return redirect(url_for('users.account'))
    
    elif request.method == 'GET':

        form.username.data = current_user.username

        form.email.data = current_user.email

        db.session.commit()

    image_file = url_for('static', filename='img/profile_pics/' + current_user.image_file)

    return render_template('account.html', title='Account - ' + current_user.username, image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):

    page = request.args.get('page', 1, type=int)

    user = User.query.filter_by(username=username).first_or_404()

    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)

    return render_template('user_posts.html', posts=posts, user=user)



@users.route("/logout")
def logout():
    
    logout_user()

    return redirect(url_for('users.login'))


@users.route('/message/<string:username>')
@login_required
def message(username):

    chat = Chat.query.all()
    user = User.query.filter_by(username=username).first_or_404()

    return render_template('message_group.html', chat=chat, username=username)

WebSite/templates/about.html
{% extends "layout.html" %}

{% block content %}
    
        <div class="jumbotron">
            <h1 class="display-4">Hello, world!</h1>
            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to
                featured content or information.</p>
            <hr class="my-4">
            <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
        </div>
    
{% endblock content %}

WebSite/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="mb-4">Perfil</legend>
                <div class="form-group">

                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}

                        {{ form.username(class="form-control form-control-lg is-invalid") }}

                        <div class="invalid-feedback">

                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}

                        </div>
                    {% else %}

                        {{ form.username(class="form-control form-control-lg") }}

                    {% endif %}
                </div>
                <div class="form-group">

                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}

                        {{ form.email(class="form-control form-control-lg is-invalid") }}

                        <div class="invalid-feedback">

                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}

                        </div>
                    {% else %}
                    
                        {{ form.email(class="form-control form-control-lg") }}

                    {% endif %}
                </div>
                <div class="form-group">

                    {{ form.picture.label() }}

                    {{ form.picture(class="form-control-file") }}

                    {% if form.picture.errors %}

                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}

                    {% endif %}
                </div>
            </fieldset>

            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
{% endblock content %}

WebSite/templates/create_post.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section justify-content-center">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

WebSite/templates/home.html
{% extends "layout.html" %}

{% block content %}
<div class="card-group">
  <div class="row">
    {% for post in posts %}

    <div class="card m-2 col-sm-3" style="width: 25rem;">
      <div class="card-header">
        <a href=" {{ url_for('users.user_posts', username=post.author.username) }} ">{{ post.author.username }}</a>
        <img class="rounded-circle "
          src="{{ url_for('static', filename='img/profile_pics/' + post.author.image_file) }}" class="card-img">
      </div>
      <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.content }}</p>
        <a href="{{ url_for('post.posts', post_id=post.id) }}" class="btn btn-primary">Ver mas</a>
      </div>
      <div class="card-footer">
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock content %}

WebSite/templates/index.html
<!doctype html>
<html lang="es">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--Bootstrap propio-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>WebSite</title>
    {% endif %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-muted">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse bg-muted" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('main.about') }}">Acerca de Nosotros<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">Contáctanos</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="jumbotron bg-muted mt-4" id="bienvenida">
            <h1 class="display-4">Hola, únete a nosotros!</h1>
            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention
                to
                featured content or information.</p>
            <hr class="my-4">
            <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
            <a class="btn btn-primary btn-lg" href="{{ url_for('users.register') }}" role="button">Registrate</a>
            <p class="text-muted">¿Ya te encuentras registrado? <a href="{{ url_for('users.login') }}">Iniciar Sesión</a></p>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

WebSite/templates/layout.html
<!doctype html>
<html lang="es">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!--Bootstrap propio-->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  {% if title %}
  <title>{{ title }}</title>
  {% else %}
  <title>WebSite</title>
  {% endif %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-transparent pr-2">
    <a class="navbar-brand" href="{{ url_for('main.home') }}">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="justify-content-center collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ">
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('main.home') }}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('users.message', username=current_user.username ) }}">Mensajes</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('post.new_post') }}">Postear</a>
        </li>
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Otras Opciones
          </a>
          <div class="dropdown-menu bg-transparent" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{{ url_for('users.account') }}">Perfil</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="{{ url_for('users.logout') }}">Cerrar Sesión</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>


  <div class="container p-4">
    <div class="row">
      <div class="col-xl-8">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}

      </div>
    </div>
  </div>

  <div class="container">
    {% block content %}{% endblock content %}
  </div>


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

WebSite/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="card w-75 bg-transparent">
    <div class="card-body">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="card-title mb-4">Inicia Sesión</legend>
            <div class="form-group card-text">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}

                    {{ form.email(class="form-control form-control-lg") }}

                {% endif %}
            </div>
            <div class="form-group card-text">
                {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}

                        {{ form.password(class="form-control form-control-lg is-invalid") }}

                        <div class="invalid-feedback">

                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}

                        </div>
                    {% else %}

                        {{ form.password(class="form-control form-control-lg") }}

                    {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}

                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">

            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        <small class="text-muted ml-2">
            <a href="#">¿Olvidaste tu contraseña?</a>
        </small>
    </form>
    </div>
</div>
<div class="pt-3">
    <small class="text-muted">
        ¿Quieres unirte a nosotros? <a class="ml-2" href="{{ url_for('users.register') }}">Registrate</a>
    </small>
</div>
{% endblock content %}

WebSite/templates/message_group.html
{% extends 'layout.html' %}

{% block content %}

<h1>Python & Socketio</h1>

<div id="app">
        <!-- Renderizará los nuevos mensajes -->
        <section>
            <div v-for="message in messages">
                <p><strong>[[ message.username ]]</strong></p>
                <p>[[ message.text ]]</p>
            </div>
        </section>
        <!-- Formulario para introducir nuevos mensajes -->
        <section>
            <input v-model="newMessage" @keypress.enter="sendMessage" type="text" placeholder="Escribe un mensaje...">
            <button @click="sendMessage">Enviar</button>
        </section>
    </div>
    <!-- Importamos socket.io -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.slim.js"></script>
    <!-- Importamos VueJS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.3/vue.min.js"></script>
    
    <script>
        // Conectamos con nuestro dominio
        var socket = io.connect();
        // Instanciamos VueJS
        var app = new Vue({
            el: "#app",
            delimiters: ['[[', ']]'],
            data: {
                username: '{{ username }}',
                // Le damos los mensajes del hitorial
                messages: [
                {% for message in chat %}
                    {
                        username: '{{ message.username }}',
                        text: '{{ message.text }}'
                    }{% if not loop.last %},{% endif %}
                {% endfor %}
                ],
                newMessage: ''
            },
            methods: {
                sendMessage: () => {
                    // Enviamos el nuevo mensaje
                    socket.emit('new_message', {
                        
                        username: app.username,
                        text: app.newMessage
                    });
                    // Clear text
                    app.$set(app, 'newMessage', '');
                }
            }
        });

        socket.on('connect', function() {
            console.log('Connect')
        });

        socket.on('new_message', function(msg) {
            // Recibimos los nuevos mensajes y los añadimos a nuestro array
            let my_messages = app.messages;
            my_messages.push({
                username: msg.username,
                text: msg.text
            })
            app.$set(app, 'messages', my_messages);
        });
    </script>

{% endblock content %}

WebSite/templates/post.html
{% extends "layout.html" %}

{% block content %}
<article class="media content-section">
  <img class="rounded-circle article-img"
    src="{{ url_for('static', filename='img/profile_pics/' + post.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
      {% if current_user.is_authenticated %}
      {% if current_user.username == post.author.username %}
      <a class="mr-2" href="{{ url_for('users.account') }}">{{ post.author.username }}</a>
      {% else %}
      <a class="mr-2"
        href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
      {% endif %}
      {% endif %}
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
      {% if post.author == current_user %}
      <div>
        <a class="btn btn-secondary btn-sm mt-1 mb-1"
          href="{{ url_for('post.update_post', post_id=post.id) }}">Editar</a>
        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
          data-target="#deleteModal">Eliminar</button>
      </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Borrar publicacion?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <form action="{{ url_for('post.delete_post', post_id=post.id) }}" method="POST">
          <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

WebSite/templates/register.html
{% extends 'layout.html' %}

{% block content %}
<div class="card w-75">
    <div class="card-body">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="card-title mb-4">Únete hoy!!</legend>
                <div class="form-group card-text">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}

                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">

                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}

                    </div>
                    {% else %}

                        {{ form.username(class="form-control form-control-lg") }}

                    {% endif %}
                </div>
                <div class="form-group card-text">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}

                        {{ form.email(class="form-control form-control-lg is-invalid") }}

                        <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}

                        </div>
                    {% else %}

                        {{ form.email(class="form-control form-control-lg") }}

                    {% endif %}
                </div>
            <div class="form-group card-text">
                {{ form.password.label(class="form-control-label") }}

                {% if form.password.errors %}

                    {{ form.password(class="form-control form-control-lg is-invalid") }}

                    <div class="invalid-feedback">

                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}

                    </div>
                {% else %}

                    {{ form.password(class="form-control form-control-lg") }}

                {% endif %}
                
            </div>
            <div class="form-group card-text">
                {{ form.confirm_password.label(class="form-control-label") }}

                {% if form.confirm_password.errors %}

                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}

                    <div class="invalid-feedback">

                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}

                    </div>

                {% else %}

                    {{ form.confirm_password(class="form-control form-control-lg") }}

                {% endif %}
            </div>
        </fieldset>

        <div class="form-group card-text">
            {{ form.submit(class="btn btn-outline-primary") }}
        </div>
    </form>
    </div>
</div>
<div class=" pt-3">
    <small class="text-muted">
        ¿Ya te encuentras registrado? <a class="ml-2 text-black" href="{{ url_for('users.login') }}">Inicia Sesión</a>
    </small>
</div>
{% endblock %}

WebSite/templates/user_posts.html
{% extends "layout.html" %}

{% block content %}

<h1 class="mb-3">Publicaciones de {{ user.username }} ({{ posts.total }})</h1>
{% for post in posts.items %}
<article class="media content-section">
  <img class="rounded-circle article-img"
    src="{{ url_for('static', filename='img/profile_pics/' + post.author.image_file) }}">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2"
        href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
    </div>
    <h2><a class="article-title" href="{{ url_for('post.posts', post_id=post.id) }}">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %}

{% endblock content %}